package hdt.petshopproject.form.home;

import hdt.petshopproject.component.Oder;
import javax.swing.JButton;

public class cardSanPham extends javax.swing.JPanel {

    public cardSanPham(int idDV,String tenDV, int giaDV) {
        initComponents();
        IdDV.setText(Integer.toString(idDV));
        TenDV.setText(tenDV);
        GiaDV.setText(Integer.toString(giaDV));
    }
    
    public cardSanPham(){
        initComponents();
    }
    
    public String getIdDV() {
        return IdDV.getText();
    }

    public String getTenDV() {
        return TenDV.getText();
    }

    public String getGiaDV() {
        return GiaDV.getText();
    }

    public JButton getAddToCart_Btn() {
        return AddToCart_Btn;
    }

    public void setAddToCart_Btn(JButton AddToCart_Btn) {
        this.AddToCart_Btn = AddToCart_Btn;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        GiaDV = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        AddToCart_Btn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        IdDV = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TenDV = new javax.swing.JLabel();
        lblAnh = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(140, 220));
        setMinimumSize(new java.awt.Dimension(140, 220));
        setPreferredSize(new java.awt.Dimension(140, 220));

        jPanel1.setBackground(new java.awt.Color(227, 227, 234));
        jPanel1.setToolTipText("");
        jPanel1.setMaximumSize(new java.awt.Dimension(130, 80));
        jPanel1.setPreferredSize(new java.awt.Dimension(130, 80));

        jLabel5.setForeground(new java.awt.Color(54, 54, 54));
        jLabel5.setText("Giá:");

        GiaDV.setForeground(new java.awt.Color(51, 51, 51));
        GiaDV.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        GiaDV.setText("x.000.000.000 ");
        GiaDV.setMaximumSize(new java.awt.Dimension(90, 16));
        GiaDV.setMinimumSize(new java.awt.Dimension(90, 16));
        GiaDV.setPreferredSize(new java.awt.Dimension(90, 16));

        jLabel11.setText("đ");

        AddToCart_Btn.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        AddToCart_Btn.setForeground(new java.awt.Color(153, 0, 51));
        AddToCart_Btn.setText("+");
        AddToCart_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddToCart_BtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("ID:");

        IdDV.setForeground(new java.awt.Color(102, 102, 102));
        IdDV.setText("D0001");

        jLabel7.setText("Loài:");

        TenDV.setForeground(new java.awt.Color(51, 51, 51));
        TenDV.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        TenDV.setText("Dogo Argentino");
        TenDV.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TenDV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(IdDV, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AddToCart_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(GiaDV, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TenDV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(GiaDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddToCart_Btn)
                    .addComponent(jLabel3)
                    .addComponent(IdDV))
                .addContainerGap())
        );

        lblAnh.setBackground(new java.awt.Color(43, 56, 97));
        lblAnh.setForeground(new java.awt.Color(255, 255, 255));
        lblAnh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAnh.setText("Ảnh");
        lblAnh.setMaximumSize(new java.awt.Dimension(140, 140));
        lblAnh.setMinimumSize(new java.awt.Dimension(140, 140));
        lblAnh.setOpaque(true);
        lblAnh.setPreferredSize(new java.awt.Dimension(140, 140));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
            .addComponent(lblAnh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(lblAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AddToCart_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddToCart_BtnActionPerformed
//        order.addToOrderPanel(Integer.parseInt(IdDV.getText()));
    }//GEN-LAST:event_AddToCart_BtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddToCart_Btn;
    private javax.swing.JLabel GiaDV;
    private javax.swing.JLabel IdDV;
    private javax.swing.JLabel TenDV;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAnh;
    // End of variables declaration//GEN-END:variables
}
